CREATE TABLE apteka
 (
 apteka_id BIGINT AUTO_INCREMENT PRIMARY KEY
 ,name VARCHAR(100) NOT NULL
 ,adress VARCHAR(100) NOT NULL
 ,phone BIGINT NOT NULL
 ,time_begin TIME NOT NULL
 ,time_end TIME NOT NULL
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 CREATE TABLE medicine
 (
 medicine_id BIGINT AUTO_INCREMENT PRIMARY KEY
 ,medicine_name VARCHAR(100) NOT NULL
 ,farmgroup_name VARCHAR(100) NOT NULL
 ,recipe VARCHAR(100) NOT NULL
 ,UNIQUE KEY (`medicine_name`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 CREATE TABLE workers
 (
 workers_id BIGINT AUTO_INCREMENT PRIMARY KEY
 ,fname VARCHAR(100) NOT NULL
 ,name VARCHAR(100) NOT NULL
 ,sname VARCHAR(100) NOT NULL
 ,work_place VARCHAR(100) NOT NULL
 ,work_position VARCHAR(100) NOT NULL
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 